version: '3.8'
services:
    mongo:
        container_name: mongo
        image: mongo:4-xenial
        ports:
            - 27017:27017
    redis:
        container_name: redis
        image: redis:5
        ports:
            - 6379:6379 
    backend:
        context: .
        dockerfile: Dockerfile
    ports:
        - 8080:8080
    volumes: :
        - .:/app