CREATE TABLE IF NOT EXISTS 'team' 
(
  `TEAM_ID` CHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`TEAM_ID`)  COMMENT ''
) ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `task` 
(
  `TASK_ID` CHAR(20) NOT NULL COMMENT '',
  `SKILL` CHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`TASK_ID`)  COMMENT ''
) ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `team_skill` 
(
  `TEAM_ID` CHAR(20) NOT NULL COMMENT '',
  `SKILL` CHAR(20) NOT NULL COMMENT '',
  CONSTRAINT 'FK_TEAM_ID'
    FOREIGN KEY ('TEAM_ID')
    REFERENCES 'team' ('TEAM_ID')
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE INDEX `FK_TEAM_ID_IDx` ON `team_skill` (`TEAM_ID` ASC)  COMMENT '';